# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "week", # <detect_control>
  "weekly_cases", # <detect_control>
  "cumulative", # <detect_control>
  "sim", # <detect_control>
  "exposure", # <outbreak_model>
  "caseid", # <outbreak_model>
  "infector", # <outbreak_model>
  "onset", # <outbreak_model>
  "i.onset", # <outbreak_model>
  "week", # <outbreak_model>
  "i.weekly_cases", # <outbreak_model>
  "cumulative", # <outbreak_model>
  "asymptomatic", # <outbreak_setup>
  "self_isolate", # <outbreak_setup>
  "isolated_time", # <outbreak_setup>
  "onset", # <outbreak_setup>
  "test_positive", # <outbreak_setup>
  "traced", # <outbreak_step>
  "exposure", # <outbreak_step>
  "infector", # <outbreak_step>
  "new_cases", # <outbreak_step>
  "sampled", # <outbreak_step>
  "caseid", # <outbreak_step>
  "isolated_time", # <outbreak_step>
  "asymptomatic", # <outbreak_step>
  "onset", # <outbreak_step>
  "self_isolate", # <outbreak_step>
  "infector_asymptomatic", # <outbreak_step>
  "self_isolation_time", # <outbreak_step>
  "test_isolation_time", # <outbreak_step>
  "traced_isolation_time", # <outbreak_step>
  "infector_isolation_time", # <outbreak_step>
  "test_positive", # <outbreak_step>
  "sampled", # <sample_offspring>
  "rand", # <allocate_tests>
  "quota", # <allocate_tests>
  "i.tests_remaining", # <allocate_tests>
  "tests_remaining", # <allocate_tests>
  "i.N", # <allocate_tests>
  "infector_isolation_time", # <sample_testing>
  "i.isolated_time", # <sample_testing>
  "n", # <sample_testing>
  "tests_remaining", # <sample_testing>
  "i.tests_remaining", # <sample_testing>
  "is_tested", # <sample_testing>
  "day", # <sample_testing>
  "infected", # <sample_testing>
  "orig_idx", # <sample_testing>
  NULL
))
