#' Move forward one generation in the branching process
#'
#' @param case_data a `data.table`: cases in outbreak so far; initially
#'   generated by [outbreak_setup()]
#' @param offspring a `list` with class `<ringbp_offspring_opts>`: the
#'   offspring distribution `function`s for the \pkg{ringbp} model, returned
#'   by [offspring_opts()]. Contains six elements: `community`, `isolated`,
#'   `asymptomatic`, and the three `*_contact_prob_infect` probabilities
#' @param delays a `list` with class `<ringbp_delay_opts>`: the
#'   delay distribution `function`s for the \pkg{ringbp} model, returned
#'   by [delay_opts()]. Contains 4 elements: `incubation_period`,
#'   `onset_to_isolation`, `latent_period` and `onset_to_self_isolation`
#' @param event_probs a `list` with class `<ringbp_event_prob_opts>`: the
#'   event probabilities for the \pkg{ringbp} model, returned by
#'   [event_prob_opts()]. Contains 5 elements: `asymptomatic`,
#'   `presymptomatic_transmission`, `alpha`, `symptomatic_traced` and
#'   `symptomatic_self_isolate`
#' @param interventions a `list` with class `<ringbp_intervention_opts>`:
#'   the intervention settings for the \pkg{ringbp} model, returned by
#'   [intervention_opts()]. Contains 4 elements: `quarantine`,
#'   `test_sensitivity`, `test_capacity` and `test_traced`. May also carry a
#'   `test_quota`
#'   element (a `data.table` of remaining capacity by day, carried over from
#'   a previous call) -- if absent, every day starts at full capacity.
#'
#' @details
#' Each new case is assigned an isolation time (`isolated_time`) as the
#' earliest of up to three pathways; a case to which no pathway applies is
#' never isolated (`isolated_time` is `Inf`):
#'
#' * **Self-isolation**: a symptomatic case self-isolates with probability
#'   `symptomatic_self_isolate` (from [event_prob_opts()]), entering isolation
#'   an `onset_to_self_isolation` delay (from [delay_opts()]) after symptom
#'   onset. Self-isolating cases are not tested.
#' * **Testing**: a symptomatic case that does not self-isolate, and has not
#'   been notified by contact tracing before its symptom onset (see
#'   **Tracing** below), is tested on its onset day. They enters isolation an
#'   `onset_to_isolation` delay (see [delay_opts()]) after the test if (a) it
#'   is allocated one of that day's tests, subject to `test_capacity`
#'   (from [intervention_opts()], shared with traced contacts tested under
#'   `test_traced` -- see [sample_testing()]), and (b) that test returns a
#'   positive result, with probability `test_sensitivity` (from
#'   [intervention_opts()]) evaluated at the test time. Neither a missed
#'   allocation nor a false-negative result isolates the case via this pathway,
#'   and the case is not retested.
#' * **Tracing**: a case whose infector is symptomatic is traced with
#'   probability `symptomatic_traced` (from [event_prob_opts()]), and is
#'   notified when its infector is isolated. A case infected while its
#'   infector is isolated is never traced: it is assumed not to know it is a
#'   contact of a case (e.g. a household member of a case isolating at
#'   home). When `quarantine` is active (from [intervention_opts()]) tracing
#'   is exposure-based: a traced case is isolated when notified, regardless
#'   of its own symptom status, and is not tested. Without `quarantine`, a
#'   traced symptomatic case is isolated no earlier than its own symptom
#'   onset. A traced case not notified by its onset (including one whose
#'   infector is never isolated) is tested at onset like an untraced case.
#' * **Contact testing** (only when `test_traced` is `TRUE` in
#'   [intervention_opts()], which requires `quarantine` to be `FALSE`): a
#'   traced case not already tested at onset (i.e. one notified before its
#'   onset, or asymptomatic) is tested when notified, regardless of symptom
#'   status, subject to the same `test_capacity` and `test_sensitivity`. If
#'   positive it enters isolation an `onset_to_isolation` delay after
#'   notification. Uninfected traced contacts are also tested when notified,
#'   using capacity but with no effect on transmission. Without
#'   `test_traced`, a traced case notified before its onset is not tested,
#'   and is isolated at its onset via tracing.
#'
#' Self-isolation and symptom-driven testing are symptom-based, so
#' asymptomatic cases are isolated only via the tracing pathway: by
#' quarantine when `quarantine` is active, or by a positive test on
#' notification when `test_traced` is active.
#'
#' @importFrom data.table data.table rbindlist fcase fifelse copy
#' @importFrom stats runif rnbinom rbinom
#'
#' @return A `list` with four elements:
#'   1. `$cases`: a `data.table` with case data
#'   2. `$effective_r0`: a `numeric` with the effective reproduction number
#'   3. `$cases_in_gen`: a `numeric` with the number of new cases in that
#'   generation
#'   4. `$test_quota`: a `data.table` (`day`, `tests_remaining`) with the
#'   remaining test capacity by day, to pass to the next call as
#'   `interventions$test_quota`
#' @autoglobal
#' @export
#'
#' @examples
#' offspring <- offspring_opts(
#'   community = \(n) rnbinom(n = n, mu = 2.5, size = 0.16),
#'   isolated = \(n) rnbinom(n = n, mu = 0, size = 1),
#'   asymptomatic = \(n) rnbinom(n = n, mu = 1.25, size = 0.16)
#' )
#' delays <- delay_opts(
#'   incubation_period = \(n) rweibull(n = n, shape = 2.32, scale = 6.49),
#'   onset_to_isolation = \(n) rweibull(n = n, shape = 1.65, scale = 4.28)
#' )
#' event_probs <- event_prob_opts(
#'   asymptomatic = 0,
#'   presymptomatic_transmission = 0.15,
#'   symptomatic_traced = 0
#' )
#' interventions <- intervention_opts(quarantine = FALSE)
#'
#' # generate initial cases
#' case_data <- outbreak_setup(
#'   initial_cases = 5,
#'   delays = delays,
#'   event_probs = event_probs,
#'   interventions = interventions
#' )
#' case_data
#' # carry the test quota that outbreak_setup() already allocated against
#' interventions$test_quota <- attr(case_data, "test_quota")
#' # generate next generation of cases
#' out <- outbreak_step(
#'   case_data = case_data,
#'   offspring = offspring,
#'   delays = delays,
#'   event_probs = event_probs,
#'   interventions = interventions
#' )
#' case_data <- out$cases
#' case_data
outbreak_step <- function(case_data,
                          offspring,
                          delays,
                          event_probs,
                          interventions) {

  checkmate::assert_data_table(case_data)
  checkmate::assert_class(offspring, "ringbp_offspring_opts")
  checkmate::assert_class(delays, "ringbp_delay_opts")
  checkmate::assert_class(event_probs, "ringbp_event_prob_opts")
  checkmate::assert_class(interventions, "ringbp_intervention_opts")

  # work with copy of case_data in outbreak_step due to
  # sample_offspring modify by reference
  case_data <- copy(case_data)

  # case_data is modified by reference; generation times for infected
  # contacts and individual rows for uninfected contacts (which also
  # compete for test capacity, see sample_testing()) are returned
  offspring_out <- sample_offspring(
    case_data = case_data,
    offspring = offspring,
    alpha = event_probs$alpha,
    latent_period = delays$latent_period
  )
  gt <- offspring_out$exposure

  # an uninfected contact only has a route into the testing queue if contact
  # tracing successfully reaches them -- it is the tracing notification that
  # prompts them to seek a test, unlike an infected contact, who may still
  # self-present once symptomatic even if tracing fails (see the testing
  # pathway below). Apply the same per-contact tracing draw used for
  # infected contacts (below), using each contact's own exposure time, then
  # collapse to the per-infector count sample_testing() expects. Traced
  # contacts are only tested when notified if `test_traced` is active; with
  # quarantine active, traced contacts are quarantined rather than tested,
  # so uninfected contacts never enter the testing queue. Contacts made
  # while the infector is isolated are never traced (see the tracing draw
  # below), so they are dropped before the draw.
  test_traced <- interventions$test_traced && !interventions$quarantine
  uninfected_dt <- offspring_out$uninfected_contacts
  if (nrow(uninfected_dt) > 0 && test_traced) {
    uninfected_dt[
      case_data, infector_isolation_time := i.isolated_time,
      on = c("infector" = "caseid")
    ]
    uninfected_dt <- uninfected_dt[exposure < infector_isolation_time]
    uninfected_dt[
      , traced := runif(.N) < event_probs$symptomatic_traced(exposure)
    ]
    traced_counts <- uninfected_dt[traced == TRUE, .N, by = infector]
    uninfected_contacts <- stats::setNames(traced_counts$N, traced_counts$infector)
  } else {
    uninfected_contacts <- integer(0)
  }

  # Select cases that have generated any new cases
  new_case_data <- case_data[new_cases > 0 & !sampled]

  # If no new cases drawn, outbreak is over so return case_data
  if (nrow(new_case_data) == 0) {
    # If everyone is sampled it means that either control has worked or
    # everyone has had a chance to infect but didn't
    case_data[, sampled := TRUE]
    out <- list(
      cases = case_data,
      effective_r0 = 0,
      cases_in_gen = 0,
      test_quota = interventions$test_quota
    )
    return(out)
  }

  # Compile a data.table for all new cases, new_cases is the amount of people
  # that each infector has infected
  prob_samples <- new_case_data[, list(
    # time when new cases were exposed, a draw from generation time based on
    # infector's onset, ordered to match order of caseid
    exposure = gt[order(as.numeric(names(gt)))],
    # records the infector of each new person
    infector = rep(caseid, new_cases),
    # records when infector was isolated
    infector_isolation_time = rep(isolated_time, new_cases),
    # records if infector asymptomatic
    infector_asymptomatic = rep(asymptomatic, new_cases),
    # cases whose parents are asymptomatic are automatically missed by tracing;
    # will draw this for infector_asymptomatic == FALSE
    traced = FALSE,
    new_cases = NA_integer_,
    sampled = FALSE,
    # assign negative test result (FALSE) as placeholder;
    # will draw test result for symptomatic cases below
    test_positive = FALSE,
    # assign no isolation as placeholder; symptomatic, test-positive,
    # traced or quarantined isolation time sampled below
    isolated_time = Inf,
    # assign no self-isolation (FALSE) as placeholder;
    # will draw self-isolation for symptomatic cases below
    self_isolate = FALSE
  )][,
    # draws a sample to see if this person is asymptomatic
    asymptomatic := runif(.N) < event_probs$asymptomatic
  ][,
    # onset of new case is exposure + incubation period sample
    onset := exposure + delays$incubation_period(.N)
  ][
    # draw a sample to see if each person self-isolates if symptomatic
    asymptomatic == FALSE,
    self_isolate := runif(.N) < event_probs$symptomatic_self_isolate
  ]

  # draw a sample for tracing. A contact made while the infector is isolated
  # (exposure after the infector's isolation time) is never traced: the
  # contact is assumed not to know they are a contact of a case (e.g.
  # household members of a case isolating at home, or staff in an isolation
  # facility), so they are treated as untraced and isolate only via the
  # symptom-based pathways
  prob_samples[
    infector_asymptomatic == FALSE & exposure < infector_isolation_time,
    traced := runif(.N) < event_probs$symptomatic_traced(exposure)
  ]

  # a traced case is notified when its infector is isolated; one notified
  # before its own symptom onset does not seek a test at onset (see the
  # testing pathway below). A traced case whose infector is isolated after
  # its onset, or never, has not been notified by onset.
  prob_samples[, notified_before_onset := traced & infector_isolation_time < onset]

  # isolation time is the earliest of three pathways; each pathway holds the
  # `Inf` placeholder for cases it does not apply to. `test_time` is the time
  # a case is tested (`Inf` if not a test candidate).
  prob_samples[, `:=`(
    self_isolation_time = Inf,
    test_time = Inf,
    test_isolation_time = Inf,
    traced_isolation_time = Inf
  )]

  # self-isolation pathway: symptomatic individuals who self-isolate are
  # isolated a self-isolation delay after symptom onset (no test required)
  prob_samples[
    self_isolate == TRUE,
    self_isolation_time := onset + delays$onset_to_self_isolation(.N)
  ]

  # testing pathway, part 1: symptomatic, non-self-isolating cases that have
  # not been notified by their onset seek a test on their onset day; this is
  # the day sample_testing() debits the test quota against. A case notified
  # before onset does not: with quarantine it is isolated when notified, and
  # without quarantine it is isolated at onset via tracing, so a test would
  # not change its isolation time. The provisional isolation time is the
  # test time plus an `onset_to_isolation` delay (the time to process the
  # test), as if a test were available and positive; it is corrected below
  # once we know which cases were actually allocated a test and which of
  # those tested positive.
  prob_samples[
    asymptomatic == FALSE & self_isolate == FALSE & !notified_before_onset,
    test_time := onset
  ]
  # testing pathway, contact testing: with `test_traced` active, a traced
  # case is tested when notified (its infector's isolation time), regardless
  # of symptom status, unless it was already tested at onset above. This
  # covers traced cases notified before their onset and asymptomatic traced
  # cases (notification is independent of whether they later self-isolate).
  if (test_traced) {
    prob_samples[
      traced & is.finite(infector_isolation_time) &
        (asymptomatic | notified_before_onset),
      test_time := infector_isolation_time
    ]
  }
  prob_samples[
    is.finite(test_time),
    test_isolation_time := test_time + delays$onset_to_isolation(.N)
  ]

  # tracing pathway: when quarantine is active it is exposure-based, so every
  # traced contact is isolated when its infector is isolated, regardless of
  # symptom status; without quarantine isolation is symptom-based, so only
  # symptomatic traced contacts are isolated, and no earlier than their own
  # symptom onset
  if (interventions$quarantine) {
    prob_samples[
      traced == TRUE,
      traced_isolation_time := infector_isolation_time
    ]
  } else {
    prob_samples[
      traced == TRUE & asymptomatic == FALSE,
      traced_isolation_time := pmax(onset, infector_isolation_time)
    ]
  }

  # testing pathway, part 2: allocate the day's test quota (shared with
  # uninfected traced contacts) and draw a test result only for cases that
  # were allocated a test; cases not allocated a test keep `test_positive`
  # at its FALSE placeholder, same as a false-negative result
  allocation <- sample_testing(
    prob_samples = prob_samples,
    uninfected_contacts = uninfected_contacts,
    case_data = case_data,
    interventions = interventions
  )
  test_quota <- allocation$test_quota
  prob_samples[
    allocation$tested,
    test_positive := runif(.N) <= interventions$test_sensitivity(test_time)
  ]
  prob_samples[test_positive == FALSE, test_isolation_time := Inf]

  # a case is isolated via the earliest pathway that applies to it
  prob_samples[, isolated_time := pmin(
    self_isolation_time, test_isolation_time, traced_isolation_time
  )]

  # Chop out unneeded sample columns
  prob_samples[
    , c("infector_isolation_time", "infector_asymptomatic", "test_positive",
        "notified_before_onset", "self_isolation_time", "test_time",
        "test_isolation_time", "traced_isolation_time") := NULL
  ]
  # Set new case ids for new people
  prob_samples[, caseid := case_data[.N, caseid] + seq_len(.N)]

  ## Number of new cases
  cases_in_gen <- nrow(prob_samples)

  ## Estimate the effective r0
  effective_r0 <- cases_in_gen / case_data[sampled == FALSE, .N]

  # Everyone in case_data so far has had their chance to infect and are
  # therefore considered isolated
  case_data[, sampled := TRUE]

  # bind original cases + new secondary cases
  case_data <- data.table::rbindlist(list(case_data, prob_samples),
                                     use.names = TRUE)

  # Return
  list(
    cases = case_data,
    effective_r0 = effective_r0,
    cases_in_gen = cases_in_gen,
    test_quota = test_quota
  )
}
